data_dir: ./data
model_dir: ./data/models
valid_ratio: .25

lr: 1e-4
loss: mse
device: cpu
epoch: 100
batch_size: 32
model_name: dnn # resnet
seed: 42
patience: 5

wandb: True # False
project: ic50-prediction
notes: "use less data to train(valid ratio .2 -> .25)"
tags: ["dacon", "ic50", "regression", "custom morgan", "valid_ratio"]
run_name: "dummy" # dummy parameter

emb_dims: [1024, 1024, 512, 512, 256, 256, 128, 128, 64, 64, 32, 32]
