data_dir: ./data
model_dir: ./data/models
valid_ratio: .2
k_fold: 5

lr: 1e-4
loss: mse
device: cuda # cpu
epoch: 100
batch_size: 32
seed: 42
patience: 10

wandb: True # False
project: ic50-prediction
notes: "concat embedding and atom embedding"
tags: ["dacon", "ic50", "regression", "custom morgan", "8-fold", "cross validation", "shuffle", "similarities", "mean reduce", "origin data", "concat"]
run_name: "dummy" # dummy parameter

model_name: dnn # resnet
layer_dims: [1024, 1024, 512, 512, 256, 256, 128, 128, 64, 64, 32, 32] #, 64, 64, 128, 128, 256, 256, 512, 512, 1024, 1024]
embed_dim: 64
type: atom # atom
