data_dir: ./data
model_dir: ./data/models

lr: 1e-4
loss: mse
device: cpu
epoch: 5
batch_size: 32
model_name: resnet

wandb: True # False
project: ic50-prediction
notes: ""
tags: ["dacon", "ic50", "regression"]
