data_dir: ./data
model_dir: ./data/models
valid_ratio: .2
k_fold: 0

lr: 1e-4
loss: mse
device: cpu
epoch: 1
batch_size: 32
seed: 42
patience: 5

wandb: False # False
project: ic50-prediction
notes: "count morgan embedding"
tags: ["dacon", "ic50", "regression", "custom morgan", "k-fold", "cross validation", "shuffle"]
run_name: "dummy" # dummy parameter

model_name: dnn # resnet
layer_dims: [1024, 1024, 512, 512, 256, 256, 128, 128, 64, 64, 32, 32]
embed_dim: 8
